version: "2.1"

services:
  web:
    build: ./backend_ceca
    command: python backend_ceca/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend_ceca
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    command: yarn start
    volumes:
      - build_front:/frontend_ceca/build
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "cecadb"
      MYSQL_USER: "ceca_user"
      MYSQL_PASSWORD: "ceca1234"
      MYSQL_ROOT_PASSWORD: "root"
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  build_front:
